{% set name = "virtualenv" %}
{% set version = "20.26.2" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/virtualenv-{{ version }}.tar.gz
  sha256: 82bf0f4eebbb78d36ddaee0283d43fe5736b53880b8a8cdcd37390a07ac3741c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python >=3.8
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
    - pip
  run:
    - python >=3.8
    - distlib <1,>=0.3.7
    - filelock <4,>=3.12.2
    - platformdirs <5,>=3.9.1

test:
  imports:
    - virtualenv
    - virtualenv.activation
  commands:
    - pip check
    - virtualenv --help
  requires:
    - pip

about:
  home: https://virtualenv.pypa.io/
  summary: Virtual Python Environment builder
  license: MIT
  license_file: LICENSE
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/en/latest/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
    - xylar
