{% set name = "virtualenv" %}
{% set version = "20.35.4" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/virtualenv-{{ version }}.tar.gz
  sha256: 643d3914d73d3eeb0c552cbb12d7e82adf0e504dbf86a3182f8771a153a1971c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
    - pip
  run:
    - typing_extensions >=4.13.2
    - python >={{ python_min }}
    - distlib >=0.3.7,<1
    - filelock >=3.12.2,<4
    - platformdirs >=3.9.1,<5

test:
  imports:
    - virtualenv
    - virtualenv.activation
  commands:
    - pip check
    - virtualenv --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://virtualenv.pypa.io/
  summary: Virtual Python Environment builder
  license: MIT
  license_file: LICENSE
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/en/latest/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
    - xylar
