{% set version = "16.7.8" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  url: https://github.com/pypa/virtualenv/archive/{{ version }}.tar.gz
  sha256: c074d3c44d8c4fab8e9dfc626ba7d4731b8c71e9f4b0b322d9d15b54ff04a554
  patches:
    - 0001-Mach-O-Copy-any-dynamic-libraries-and-symlinks-to-th.patch
    - 0002-ELF-Copy-any-dynamic-libraries-and-symlinks-to-the-c.patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - virtualenv = virtualenv:main

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  commands:
    - virtualenv --help
    # Skipping py2k tests b/c it fails on our docker image
    # but I'm 99% sure it should work locally.
    - |
      virtualenv -p "$(which python)" /tmp/venv-$$  # [not win]
      source /tmp/venv-$$/bin/activate  # [not win]
      python -c 'import sys ; sys.exit(not hasattr(sys, "real_prefix"))'  # [not win]
  imports:
    - virtualenv

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Virtual Python Environment builder
  description: |
    virtualenv is a tool to create isolated Python environments.
  doc_url: https://virtualenv.pypa.io/en/latest/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
