{% set version = "20.0.20" %}

package:
  name: virtualenv
  version: {{ version }}

source:
  git_url: https://github.com/pypa/virtualenv.git
  git_rev: {{ version }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python
    - pip >=18
    - setuptools >=41
    - setuptools_scm >=2
  run:
    - python
    - appdirs >=1.4.3,<2
    - distlib >=0.3.0,<1
    - filelock >=3.0.0,<4
    - six >=1.9.0,<2   # keep it >=1.9.0 as it may cause problems on LTS platforms
    - contextlib2 >=0.6.0,<1  # [py<33]
    - importlib-metadata >=0.12,<2  # [py<38]
    - importlib_resources >=1.0,<2  # [py<37]
    - pathlib2 >=2.3.3,<3  # [py<34 and not win]

test:
  commands:
    - virtualenv --help
    - virtualenv .env

  imports:
    - virtualenv

about:
  home: https://virtualenv.pypa.io/
  license: MIT
  license_file: LICENSE
  summary: Virtual Python Environment builder
  description: |
    A tool for creating isolated virtual python environments.
  doc_url: https://virtualenv.pypa.io/en/latest/
  dev_url: https://github.com/pypa/virtualenv

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
