schema_version: 1

context:
  name: virtualenv
  version: 20.39.0

package:
  name: virtualenv
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/virtualenv-${{ version }}.tar.gz
  sha256: a15f0cebd00d50074fd336a169d53422436a12dfe15149efec7072cfe817df8b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - virtualenv = virtualenv.__main__:run_with_catch

requirements:
  host:
    - python ${{ python_min }}.*
    - hatch-vcs >=0.3
    - hatchling >=1.17.1
    - pip
  run:
    - python >=${{ python_min }}
    - distlib >=0.3.7,<1
    - platformdirs >=3.9.1,<5
    - typing_extensions >=4.13.2
    - importlib-metadata >=6.6
tests:
  - python:
      imports:
        - virtualenv
        - virtualenv.activation
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - virtualenv --help

about:
  summary: Virtual Python Environment builder
  license: MIT
  license_file: LICENSE
  description: |
    A tool for creating isolated virtual python environments.
  homepage: https://virtualenv.pypa.io/
  repository: https://github.com/pypa/virtualenv
  documentation: https://virtualenv.pypa.io/en/latest/

extra:
  recipe-maintainers:
    - mingwandroid
    - kalefranz
    - xylar
